name: Robot INGCOM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v3
    - name: Configurando Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Instalando dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pycodestyle
        pip install pytest pytest-cov
    - name: Analizando el estilo de programación (PEP8)
      run: |
        pycodestyle --show-source $(git ls-files '*.py')
    - name: Analizando el código con pylint
      run: |
        pylint --fail-under 4 -v $(git ls-files '*.py')
    - name: Ejecutando los tests con cobertura
      run: |
        export PYTHONPATH=src
        python -m pytest -v --cov=src
